words = [
	"arktype",
	"bundler",
	"consola",
	"esm",
	"ianitor",
	"iex",
	"irm",
	"knip",
	"oxc",
	"oxfmt",
	"oxlint",
	"picocolors",
	"profilebegin",
	"profileend",
	"tsc",
	"tsgo",
	"tsgolint",
	"typebox",
]
