words = [
    "arktype",
    "bundler",
    "consola",
    "esm",
    "ianitor",
    "iex",
    "irm",
    "jsr",
    "knip",
    "oxc",
    "oxfmt",
    "oxlint",
    "picocolors",
    "profilebegin",
    "profileend",
    "rbxts",
    "tsc",
    "tsgo",
    "tsgolint",
    "typebox",
    "unmemoized",
    "vfc",
]
